# Surcharge production
# Usage : docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:

  db:
    restart: always
    deploy:
      resources:
        limits:
          memory: 512m

  api:
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Serilog__MinimumLevel__Default: Warning
    deploy:
      resources:
        limits:
          memory: 512m
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  web:
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    deploy:
      resources:
        limits:
          memory: 256m
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
